SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE answers;
TRUNCATE TABLE questions;
TRUNCATE TABLE articles;
TRUNCATE TABLE question_tags;
TRUNCATE TABLE tags;
TRUNCATE TABLE profiles;
TRUNCATE TABLE users;

SET REFERENTIAL_INTEGRITY TRUE;